# Generated by Django 4.2.7 on 2025-11-25 07:46

from django.db import migrations, models
import hair_transformation.models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_transformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairtransformation',
            name='hair_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hairtransformation',
            name='hair_mask_image',
            field=models.ImageField(blank=True, null=True, upload_to=hair_transformation.models.result_upload_path),
        ),
    ]
