# Generated by Django 4.2.7 on 2025-11-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_transformation', '0002_hairtransformation_hair_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairtransformation',
            name='processing_step',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hairtransformation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
